In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Import fumble Dataset
fumble = pd.read_csv("../Resources/Career_Stats_Fumbles.csv")

In [3]:
# Visualize Dataset
fumble.head()

,Player Id,Name,Position,Year,Team,Games Played,Fumbles,Fumbles Lost,Forced Fumbles,Own Fumbles Recovered,Opponent Fumbles Recovered,Own Fumble Return Yards,Opponent Fumble Return Yards,Fumble Return TDs,Out of Bounds Fumbles,Saftey Fumbles,Touchbacks
0,joeadams/2532782,"Adams, Joe",NaN,2012,Carolina Panthers,9,4,3,--,1,--,0,--,--,0,0,0
1,clarenceverdin/2503464,"Verdin, Clarence",NaN,1994,Atlanta Falcons,12,3,1,--,2,--,0,--,--,0,0,0
2,clarenceverdin/2503464,"Verdin, Clarence",NaN,1993,Indianapolis Colts,16,3,2,--,1,--,0,--,--,0,0,0
3,clarenceverdin/2503464,"Verdin, Clarence",NaN,1992,Indianapolis Colts,16,2,1,--,--,--,--,--,--,0,0,0
4,clarenceverdin/2503464,"Verdin, Clarence",NaN,1991,Indianapolis Colts,16,2,0,0,1,1,0,0,0,0,0,0

In [4]:
# Drop unecessary columns
fumble.drop(["Player Id", "Name", "Position", "Games Played", "Fumbles", "Own Fumbles Recovered", "Opponent Fumbles Recovered",
            "Out of Bounds Fumbles", "Saftey Fumbles", "Touchbacks"], axis = 1, inplace = True)

In [5]:
# Format year colum
fumble["Year"] = fumble["Year"].astype(str)

# Format team column
fumble["Team"] = [row.lower() for row in fumble["Team"]]
fumble["Team"] = fumble["Team"].str.replace('.','')
fumble["Team"] = fumble["Team"].str.replace(' ','_')

/Users/Alvarado/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

In [6]:
# Format colnames
fumble.set_axis(["year", "team", "fumbles_lost_fum", "forced_fumbles_fum", "own_fumble_return_yards_fum",
                 "opponent_fumble_return_yards_fum", "fumble_return_tds_fum"], 
                 axis = 1, inplace = True)

In [7]:
# Get stats cols
stats_cols = ["fumbles_lost_fum", "forced_fumbles_fum", "own_fumble_return_yards_fum",
                 "opponent_fumble_return_yards_fum", "fumble_return_tds_fum"]

In [8]:
# Replace "--" with "0"
for col in stats_cols:
    fumble[col] = fumble[col].astype(str).str.replace('--','0')
    fumble[col] = fumble[col].astype(str).str.replace(',','').astype(int)

In [9]:
# Value counts
for col in stats_cols:
    print(f"{col}")
    print(fumble[f"{col}"].value_counts())
    print(" ")

fumbles_lost_fum
0     8278
1     1760
2      629
3      313
4      143
5       80
6       52
7       24
8        7
9        2
11       1
Name: fumbles_lost_fum, dtype: int64

forced_fumbles_fum
0     10461
1       561
2       172
3        65
4        17
5         6
7         3
6         2
8         1
10        1
Name: forced_fumbles_fum, dtype: int64

own_fumble_return_yards_fum
 0     11143
 2        16
 4        15
 1        15
-2        11
-1        10
 5         8
 3         7
 15        5
 8         5
-4         5
-3         4
 11        4
 6         4
 9         3
 7         3
 16        3
-8         3
 18        3
-6         2
-7         2
-5         2
 12        2
 17        1
 10        1
 58        1
 21        1
 64        1
 27        1
 13        1
-14        1
 20        1
 23        1
 33        1
-11        1
 57        1
-9         1
Name: own_fumble_return_yards_fum, dtype: int64

opponent_fumble_return_yards_fum
0     10901
1        28
2        24
4        20
6        17
      ...
49        1
54        1
31        1
68        1
42        1
Name: opponent_fumble_return_yards_fum, Length: 80, dtype: int64

fumble_return_tds_fum
0    11172
1      115
2        2
Name: fumble_return_tds_fum, dtype: int64

In [10]:
# Create unique identifier
fumble["team_year"] = fumble["team"] + "_" + fumble["year"]

In [11]:
# Order columns and delete year and team
fumble = fumble[["team_year", "fumbles_lost_fum", "forced_fumbles_fum", "own_fumble_return_yards_fum",
                 "opponent_fumble_return_yards_fum", "fumble_return_tds_fum"]]

In [12]:
# Create groupby using unique identifier
fumble_df = fumble.groupby("team_year").sum()
fumble_df

,fumbles_lost_fum,forced_fumbles_fum,own_fumble_return_yards_fum,opponent_fumble_return_yards_fum,fumble_return_tds_fum
team_year,,,,,
arizona_cardinals_1994,6,0,27,2,0
arizona_cardinals_1995,3,0,0,0,0
arizona_cardinals_1996,8,0,0,0,0
arizona_cardinals_1997,7,0,0,0,0
arizona_cardinals_1998,5,0,0,0,0
...,...,...,...,...,...
washington_redskins_2012,5,1,5,7,0
washington_redskins_2013,13,4,0,75,1
washington_redskins_2014,12,1,0,17,0
washington_redskins_2015,11,4,0,17,1
washington_redskins_2016,9,4,7,0,0

In [13]:
# Write clean dataset
fumble_df.to_csv("../Resources/clean_fumbles.csv", header = True, index = True)